# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*


BROWSERSYNC:
  notify: true
  open:   false
  port:   3000
  server:
    basedir: "_site/"
  xip:    true

CLEAN: "_site/"

COPY:
  # Paths to static assets that aren't (S)CSS or JavaScript
  # because these are completely handled by the sass and javascript tasks
  assets:
    # all files below the assets dir
    - "assets/**/*"
    # exclusions:
    - "!assets/{js,scss,css}/**/*"   # js, scss and css files
    - "!assets/css{,/**}"            # css dir
    - "!assets/js{,/**}"             # js dir
    - "!assets/scss{,/**}"           # scss dir
    - "!assets/vendor{,/**}"         # vendor dir
  dist: "_site/assets/"
  notification: "Running Copy"

JAVASCRIPT:
  dest:
    jekyllRoot: "assets/js/"
    buildDir: "_site/assets/js/"
  # filename to output
  filename: "all.js"
  notification: "Running JavaScript"
  # Paths to JavaScript libraries, which are combined into one file
  src: "assets/js/*.js"
    # Paths to your own project code are here
    # All the files in this list and in the js dir are concatenated into all.js

MODERNIZR:
  notification: "Running Modernizr"
  dest:
    jekyllRoot: "assets/js/"
  filename: "modernizr.js"
  src:
   - assets/js/app.js

JEKYLL:
  notification: "Running jekyll"

SASS:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:
    - "last 2 versions"
    - "ie >= 9"
  dest:
    jekyllRoot: "assets/css/"
    buildDir: "_site/assets/css/"
  notification: "Running Sass"
  src: "assets/*.scss"
  include:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"

WATCH:
  media:
    - "assets/img/**/*"
    - "assets/video/**/*"
    - "_uploads/*"
  javascript:
    - "assets/js/*.js"
    - "assets/js/**/*.js"
  sass: "_sass/**/*.scss"
  pages:
    - "*.{md,markdown,html,yml,xml}"
    - "{_data,_includes,_layouts,_actualites,_communiques,_evenements,_missions-dinsic,_pages,_politique-logiciel-libre,_posts,_rechercher,blog,actualites}/**/*.{md,markdown,html,yml,xml}"
    - "!_site/**/*.*"
    - "!assets/**/*.*"
